### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [gonzalo-github/prj-rev-bwfs-dasmoto#6]
**Grade:** Needs Improvement

**Summary:** This project has a lot of good work in it! Overall the basics of the project are covered well, but there’s just a few small issues that need to be fixed. Make sure to use relative links and not absolute links (css/image links). This will fix a missing image issue. Also, reviewing your CSS and focusing on consistent code spacing will make your styles much more readable! Lastly, trying to wrap related HTML code with container divs, which will make styling and layout with CSS much easier in the future! Another is to try and use one selector in your CSS like body to apply a style instead of multiple individual elements.

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline-block.html.

Good luck!

**Comment by gonzalo-github** [comment]
Dear grifin lacek
   I appreciate your comments and suggestions that I will try to take into account in the next tasks of the course. As a return I commented that the reviewers should keep in mind that many of us who do the course do not have previous experience in web design, so the comments should be as detailed as possible so that we can understand and apply.
Thanks and regards.
        Gonzalo
